### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by yisibl** [fuzhenn/node-svg2img#68]
- [ ] https://github.com/fuzhenn/node-svg2img/pull/66
- [ ] Add ESLint config
- [ ] CI Switching to GitHub actions
- [ ] Reduce dependencies and control package size.

**Comment by fuzhenn** [comment]
github action测试都失败了，请看看是咋回事

**Comment by fuzhenn** [comment]
噢，是remote svg那个测试用例出错了
